### ISSUE TITLE
.gitignore perhaps incorrectly ignoring the next-drupal-debug directory?

### ISSUE THREAD

**Issue by li-joel-arnott** [platformsh-templates/nextjs-drupal#12] opened 2023-09-12 11:07 UTC
I just tried deploying a copy of this template to platform.sh via GitHub but the build failed due to not finding the `next-drupal-debug`  directory, presumably because it's inside the .gitignore file. It seems to have been committed prior to being added to the .gitignore file. I have since removed it from my own .gitignore which fixed the build.

Is it correct that it's being .gitignore'd?

**Comment by li-joel** [comment] 2023-09-12 11:16
Actually... I know the problem - this was caused by downloading a zip and committing into our own repo rather than cloning and changing the remote (which would've ensured the directory existed). All good - closing...

**Closed as completed by li-joel** 2023-09-12 11:16 UTC
